FAILURE_TYPES = [
    "connection_pool_exhaustion",
    "oom_killed",
    "network_partition",
    "disk_full",
    "cpu_saturation",
    "deadlock",
    "memory_leak",
    "timeout",
    "broker_unavailable",
    "infinite_loop",
    "query_overload",
    "certificate_expired",
    "dns_resolution_failure",
    "rate_limit_exceeded",
    "dependency_unavailable",
    "kafka_disk_pressure",
    "redis_failover_storm",
    "ssl_tls_handshake_failure",
    "database_connection_exhaustion",
    "pod_crash_loop",
    "replication_lag",
    "disk_io_saturation",
    "garbage_collection_storm",
]

FIX_TYPES = [
    "restart_service",
    "increase_pool_size",
    "rollback_deployment",
    "scale_horizontally",
    "clear_cache",
    "increase_memory_limit",
    "fix_memory_leak",
    "add_circuit_breaker",
    "reduce_query_load",
    "move_to_read_replica",
    "add_exponential_backoff",
    "free_disk_space",
    "renew_certificate",
    "reduce_log_retention",
    "add_autoscaler",
    "add_index",
    "increase_connection_timeout",
    "scale_vertically",
    "rebalance_partitions",
    "optimize_query_plan",
    "upgrade_oom_limits",
]

SYMPTOM_TYPES = [
    "high_latency",
    "request_timeout",
    "cpu_spike",
    "memory_spike",
    "error_rate_increase",
    "service_unavailable",
    "connection_refused",
    "queue_backup",
    "data_inconsistency",
    "pod_restarts",
    "5xx_errors",
    "slow_queries",
    "connection_pool_exhausted",
    "disk_pressure",
    "certificate_errors",
    "retry_storm",
    "gc_pause_spike",
    "replication_delay",
]

SEVERITY_LEVELS = ["low", "medium", "high", "critical"]

ENVIRONMENTS = ["dev", "staging", "production"]

SERVICE_ALIASES: dict[str, str] = {
    "checkout": "checkout",
    "checkout-service": "checkout",
    "checkout api": "checkout",
    "checkout api service": "checkout",
    "payment": "payment",
    "payment-service": "payment",
    "payment api": "payment",
    "payment service": "payment",
    "billing api": "api",
    "billing service": "billing",
    "session": "session",
    "session-service": "session",
    "session service": "session",
    "auth": "auth",
    "auth-service": "auth",
    "authentication": "auth",
    "gateway": "gateway",
    "api gateway": "gateway",
    "api-gateway": "gateway",
    "order-processor": "order-processor",
    "order processor": "order-processor",
    "orders": "orders",
    "order service": "order-service",
    "order-service": "order-service",
    "notification-service": "notification-service",
    "notification service": "notification-service",
    "analytics-processor": "analytics-processor",
    "analytics processor": "analytics-processor",
    "event-processor": "event-processor",
    "event processor": "event-processor",
    "payment-worker": "payment-worker",
    "payment worker": "payment-worker",
    "inventory": "inventory",
    "cache": "cache",
}

COMPONENT_ALIASES: dict[str, str] = {
    "redis": "redis",
    "redis cluster": "redis",
    "redis sentinel": "redis",
    "redis node": "redis",
    "redis failover": "redis",
    "kafka": "kafka",
    "kafka broker": "kafka",
    "kafka brokers": "kafka",
    "kafka cluster": "kafka",
    "kafka storage": "kafka",
    "kafka disk": "kafka",
    "kafka topic": "kafka",
    "kafka producer": "kafka",
    "kafka consumer": "kafka",
    "postgresql": "postgresql",
    "postgres": "postgresql",
    "postgres db": "postgresql",
    "postgres database": "postgresql",
    "pg": "postgresql",
    "mysql": "mysql",
    "mongodb": "mongodb",
    "mongo": "mongodb",
    "elasticsearch": "elasticsearch",
    "es": "elasticsearch",
    "nginx": "nginx",
    "nginx ingress": "nginx",
    "nginx mesh": "nginx",
    "rabbitmq": "rabbitmq",
    "rmq": "rabbitmq",
    "cpu": "cpu",
    "processor": "cpu",
    "memory": "memory",
    "mem": "memory",
    "ram": "memory",
    "disk": "disk",
    "storage": "disk",
    "volume": "disk",
    "ssd": "disk",
    "network": "network",
    "net": "network",
    "dns": "dns",
    "dns resolver": "dns",
    "tls": "nginx",
    "ssl": "nginx",
    "certificate": "nginx",
}

FAILURE_TYPE_ALIASES: dict[str, str] = {
    "connection pool exhaustion": "connection_pool_exhaustion",
    "connection_pool_exhaustion": "connection_pool_exhaustion",
    "pool exhaustion": "connection_pool_exhaustion",
    "pool exhausted": "connection_pool_exhaustion",
    "no free connections": "connection_pool_exhaustion",
    "connection pool full": "connection_pool_exhaustion",
    "all client slots busy": "connection_pool_exhaustion",
    "connection capacity exhausted": "connection_pool_exhaustion",
    "oom killed": "oom_killed",
    "oom_killed": "oom_killed",
    "out of memory": "oom_killed",
    "oom": "oom_killed",
    "oom kill": "oom_killed",
    "killed by oom": "oom_killed",
    "network partition": "network_partition",
    "network_partition": "network_partition",
    "split brain": "network_partition",
    "node isolation": "network_partition",
    "disk full": "disk_full",
    "disk_full": "disk_full",
    "no space left": "disk_full",
    "disk space exhausted": "disk_full",
    "disk 95%": "disk_full",
    "read-only state": "disk_full",
    "storage full": "disk_full",
    "kafka disk full": "kafka_disk_pressure",
    "kafka_disk_pressure": "kafka_disk_pressure",
    "kafka disk pressure": "kafka_disk_pressure",
    "kafka storage pressure": "kafka_disk_pressure",
    "kafka broker storage": "kafka_disk_pressure",
    "broker disk filled": "kafka_disk_pressure",
    "kafka retention": "kafka_disk_pressure",
    "kafka rejected writes": "kafka_disk_pressure",
    "cpu saturation": "cpu_saturation",
    "cpu_saturation": "cpu_saturation",
    "cpu spike": "cpu_saturation",
    "cpu 100%": "cpu_saturation",
    "100% cpu": "cpu_saturation",
    "high cpu": "cpu_saturation",
    "cpu pinned": "cpu_saturation",
    "cpu burn": "cpu_saturation",
    "deadlock": "deadlock",
    "database deadlock": "deadlock",
    "lock contention": "deadlock",
    "memory leak": "memory_leak",
    "memory_leak": "memory_leak",
    "heap growth": "memory_leak",
    "heap exhaustion": "memory_leak",
    "timeout": "timeout",
    "request timeout": "timeout",
    "request_timeout": "timeout",
    "timed out": "timeout",
    "timing out": "timeout",
    "connection timeout": "timeout",
    "read timeout": "timeout",
    "write timeout": "timeout",
    "redis timeout": "timeout",
    "redis failover storm": "redis_failover_storm",
    "redis_failover_storm": "redis_failover_storm",
    "redis failover": "redis_failover_storm",
    "redis node election": "redis_failover_storm",
    "cache failover storm": "redis_failover_storm",
    "immediate retry on failover": "redis_failover_storm",
    "retry storm after failover": "redis_failover_storm",
    "broker unavailable": "broker_unavailable",
    "broker_unavailable": "broker_unavailable",
    "broker down": "broker_unavailable",
    "infinite loop": "infinite_loop",
    "infinite_loop": "infinite_loop",
    "infinite retry": "infinite_loop",
    "retry loop": "infinite_loop",
    "endless loop": "infinite_loop",
    "query overload": "query_overload",
    "query_overload": "query_overload",
    "slow query": "query_overload",
    "slow queries": "query_overload",
    "full table scan": "query_overload",
    "missing index": "query_overload",
    "unindexed query": "query_overload",
    "query storm": "query_overload",
    "database scan": "query_overload",
    "certificate expired": "certificate_expired",
    "certificate_expired": "certificate_expired",
    "tls expired": "certificate_expired",
    "ssl expired": "certificate_expired",
    "certificate expiry": "certificate_expired",
    "stale certificate": "certificate_expired",
    "missed certificate rotation": "certificate_expired",
    "certificate rotation": "certificate_expired",
    "ssl_tls_handshake_failure": "ssl_tls_handshake_failure",
    "ssl/tls handshake failure": "ssl_tls_handshake_failure",
    "tls handshake failure": "ssl_tls_handshake_failure",
    "tls error": "ssl_tls_handshake_failure",
    "dns resolution failure": "dns_resolution_failure",
    "dns_resolution_failure": "dns_resolution_failure",
    "dns lookup failure": "dns_resolution_failure",
    "dns resolution": "dns_resolution_failure",
    "rate limit exceeded": "rate_limit_exceeded",
    "rate_limit_exceeded": "rate_limit_exceeded",
    "rate limited": "rate_limit_exceeded",
    "429 error": "rate_limit_exceeded",
    "too many requests": "rate_limit_exceeded",
    "dependency unavailable": "dependency_unavailable",
    "dependency_unavailable": "dependency_unavailable",
    "dependency down": "dependency_unavailable",
    "upstream unavailable": "dependency_unavailable",
    "database connection exhaustion": "database_connection_exhaustion",
    "database_connection_exhaustion": "database_connection_exhaustion",
    "db connection pool exhausted": "database_connection_exhaustion",
    "pg connection exhaustion": "database_connection_exhaustion",
    "pod crash loop": "pod_crash_loop",
    "pod_crash_loop": "pod_crash_loop",
    "crashloopbackoff": "pod_crash_loop",
    "pod restarting": "pod_crash_loop",
    "replication lag": "replication_lag",
    "replication_lag": "replication_lag",
    "replica delay": "replication_lag",
    "sync delay": "replication_lag",
    "disk io saturation": "disk_io_saturation",
    "disk_io_saturation": "disk_io_saturation",
    "io bottleneck": "disk_io_saturation",
    "iowait spike": "disk_io_saturation",
    "garbage collection storm": "garbage_collection_storm",
    "garbage_collection_storm": "garbage_collection_storm",
    "gc storm": "garbage_collection_storm",
    "gc pause spike": "garbage_collection_storm",
    "long gc pauses": "garbage_collection_storm",
}

FIX_TYPE_ALIASES: dict[str, str] = {
    "restart service": "restart_service",
    "restart_service": "restart_service",
    "restart": "restart_service",
    "service restart": "restart_service",
    "reboot": "restart_service",
    "increase pool size": "increase_pool_size",
    "increase_pool_size": "increase_pool_size",
    "expand pool": "increase_pool_size",
    "scale pool": "increase_pool_size",
    "bigger pool": "increase_pool_size",
    "pool size increase": "increase_pool_size",
    "add more connections": "increase_pool_size",
    "rollback deployment": "rollback_deployment",
    "rollback_deployment": "rollback_deployment",
    "rollback": "rollback_deployment",
    "revert deploy": "rollback_deployment",
    "revert release": "rollback_deployment",
    "scale horizontally": "scale_horizontally",
    "scale_horizontally": "scale_horizontally",
    "horizontal scale": "scale_horizontally",
    "add instances": "scale_horizontally",
    "more replicas": "scale_horizontally",
    "scale out": "scale_horizontally",
    "clear cache": "clear_cache",
    "clear_cache": "clear_cache",
    "flush cache": "clear_cache",
    "evict cache": "clear_cache",
    "increase memory limit": "increase_memory_limit",
    "increase_memory_limit": "increase_memory_limit",
    "more memory": "increase_memory_limit",
    "memory limit increase": "increase_memory_limit",
    "bump memory": "increase_memory_limit",
    "upgrade oom limits": "upgrade_oom_limits",
    "upgrade_oom_limits": "upgrade_oom_limits",
    "oom limit increase": "upgrade_oom_limits",
    "fix memory leak": "fix_memory_leak",
    "fix_memory_leak": "fix_memory_leak",
    "patch leak": "fix_memory_leak",
    "memory leak fix": "fix_memory_leak",
    "add circuit breaker": "add_circuit_breaker",
    "add_circuit_breaker": "add_circuit_breaker",
    "circuit breaker": "add_circuit_breaker",
    "enable circuit breaker": "add_circuit_breaker",
    "reduce query load": "reduce_query_load",
    "reduce_query_load": "reduce_query_load",
    "throttle queries": "reduce_query_load",
    "limit queries": "reduce_query_load",
    "add index": "add_index",
    "add_index": "add_index",
    "create index": "add_index",
    "create an index": "add_index",
    "add missing index": "add_index",
    "create missing index": "add_index",
    "index the table": "add_index",
    "build index": "add_index",
    "move to read replica": "move_to_read_replica",
    "move_to_read_replica": "move_to_read_replica",
    "read replica": "move_to_read_replica",
    "use replica": "move_to_read_replica",
    "add read replica": "move_to_read_replica",
    "add exponential backoff": "add_exponential_backoff",
    "add_exponential_backoff": "add_exponential_backoff",
    "exponential backoff": "add_exponential_backoff",
    "backoff": "add_exponential_backoff",
    "add retry backoff": "add_exponential_backoff",
    "backoff strategy": "add_exponential_backoff",
    "retry with backoff": "add_exponential_backoff",
    "free disk space": "free_disk_space",
    "free_disk_space": "free_disk_space",
    "clean disk": "free_disk_space",
    "cleanup disk": "free_disk_space",
    "remove old data": "free_disk_space",
    "renew certificate": "renew_certificate",
    "renew_certificate": "renew_certificate",
    "rotate certificate": "renew_certificate",
    "certificate renewal": "renew_certificate",
    "tls renewal": "renew_certificate",
    "rotate tls": "renew_certificate",
    "reduce log retention": "reduce_log_retention",
    "reduce_log_retention": "reduce_log_retention",
    "lower retention": "reduce_log_retention",
    "retention policy": "reduce_log_retention",
    "shorten retention": "reduce_log_retention",
    "add autoscaler": "add_autoscaler",
    "add_autoscaler": "add_autoscaler",
    "enable autoscaler": "add_autoscaler",
    "hpa": "add_autoscaler",
    "increase connection timeout": "increase_connection_timeout",
    "increase_connection_timeout": "increase_connection_timeout",
    "longer timeout": "increase_connection_timeout",
    "bump timeout": "increase_connection_timeout",
    "scale vertically": "scale_vertically",
    "scale_vertically": "scale_vertically",
    "vertical scale": "scale_vertically",
    "bigger instance": "scale_vertically",
    "upgrade instance": "scale_vertically",
    "rebalance partitions": "rebalance_partitions",
    "rebalance_partitions": "rebalance_partitions",
    "kafka rebalance": "rebalance_partitions",
    "consumer group rebalance": "rebalance_partitions",
    "optimize query plan": "optimize_query_plan",
    "optimize_query_plan": "optimize_query_plan",
    "query optimization": "optimize_query_plan",
    "tune query plan": "optimize_query_plan",
    "rewrite query": "optimize_query_plan",
}

SEVERITY_ALIASES: dict[str, str] = {
    "low": "low",
    "minor": "low",
    "info": "low",
    "p3": "low",
    "sev3": "low",
    "sev-3": "low",
    "medium": "medium",
    "moderate": "medium",
    "p2": "medium",
    "sev2": "medium",
    "sev-2": "medium",
    "warning": "medium",
    "high": "high",
    "major": "high",
    "p1": "high",
    "sev1": "high",
    "sev-1": "high",
    "severe": "high",
    "degraded": "high",
    "critical": "critical",
    "p0": "critical",
    "sev0": "critical",
    "sev-0": "critical",
    "outage": "critical",
    "down": "critical",
    "p0 outage": "critical",
    "full outage": "critical",
    "sev0 outage": "critical",
    "sev-0 outage": "critical",
}

SYMPTOM_ALIASES: dict[str, str] = {
    "high latency": "high_latency",
    "high_latency": "high_latency",
    "slow response": "high_latency",
    "slow responses": "high_latency",
    "slow api": "high_latency",
    "degraded latency": "high_latency",
    "request timeout": "request_timeout",
    "request_timeout": "request_timeout",
    "timed out": "request_timeout",
    "timeout": "request_timeout",
    "connection timeout": "request_timeout",
    "cpu spike": "cpu_spike",
    "cpu_spike": "cpu_spike",
    "high cpu": "cpu_spike",
    "cpu at 100": "cpu_spike",
    "100% cpu": "cpu_spike",
    "cpu burn": "cpu_spike",
    "memory spike": "memory_spike",
    "memory_spike": "memory_spike",
    "high memory": "memory_spike",
    "memory usage spike": "memory_spike",
    "oom": "memory_spike",
    "heap growth": "memory_spike",
    "error rate increase": "error_rate_increase",
    "error_rate_increase": "error_rate_increase",
    "rising errors": "error_rate_increase",
    "error spike": "error_rate_increase",
    "error rate spike": "error_rate_increase",
    "elevated error rate": "error_rate_increase",
    "service unavailable": "service_unavailable",
    "service_unavailable": "service_unavailable",
    "service down": "service_unavailable",
    "service degraded": "service_unavailable",
    "connection refused": "connection_refused",
    "connection_refused": "connection_refused",
    "refused connection": "connection_refused",
    "connection rejected": "connection_refused",
    "queue backup": "queue_backup",
    "queue_backup": "queue_backup",
    "queue backlog": "queue_backup",
    "message queue backup": "queue_backup",
    "consumer lag": "queue_backup",
    "data inconsistency": "data_inconsistency",
    "data_inconsistency": "data_inconsistency",
    "data drift": "data_inconsistency",
    "stale data": "data_inconsistency",
    "pod restarts": "pod_restarts",
    "pod_restarts": "pod_restarts",
    "pod restarting": "pod_restarts",
    "crashloop": "pod_restarts",
    "crashloopbackoff": "pod_restarts",
    "restarts": "pod_restarts",
    "5xx errors": "5xx_errors",
    "5xx_errors": "5xx_errors",
    "504": "5xx_errors",
    "503": "5xx_errors",
    "502": "5xx_errors",
    "500": "5xx_errors",
    "server errors": "5xx_errors",
    "slow queries": "slow_queries",
    "slow_queries": "slow_queries",
    "database slow": "slow_queries",
    "query latency": "slow_queries",
    "query slowness": "slow_queries",
    "full table scan": "slow_queries",
    "connection pool exhausted": "connection_pool_exhausted",
    "connection_pool_exhausted": "connection_pool_exhausted",
    "pool full": "connection_pool_exhausted",
    "no free connections": "connection_pool_exhausted",
    "disk pressure": "disk_pressure",
    "disk_pressure": "disk_pressure",
    "disk high": "disk_pressure",
    "storage pressure": "disk_pressure",
    "disk usage high": "disk_pressure",
    "certificate errors": "certificate_errors",
    "certificate_errors": "certificate_errors",
    "tls errors": "certificate_errors",
    "ssl errors": "certificate_errors",
    "tls handshake failed": "certificate_errors",
    "retry storm": "retry_storm",
    "retry_storm": "retry_storm",
    "retry amplification": "retry_storm",
    "thundering herd": "retry_storm",
    "massive retries": "retry_storm",
    "gc pause spike": "gc_pause_spike",
    "gc_pause_spike": "gc_pause_spike",
    "long gc pauses": "gc_pause_spike",
    "garbage collection pauses": "gc_pause_spike",
    "replication delay": "replication_delay",
    "replication_delay": "replication_delay",
    "replica lag": "replication_delay",
    "sync delay": "replication_delay",
}

ENVIRONMENT_ALIASES: dict[str, str] = {
    "dev": "dev",
    "development": "dev",
    "local": "dev",
    "staging": "staging",
    "stage": "staging",
    "pre-prod": "staging",
    "preprod": "staging",
    "preproduction": "staging",
    "production": "production",
    "prod": "production",
    "live": "production",
}
